// <auto-generated />
namespace DEMO_SERVER.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddRemarksField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRemarksField));
        
        string IMigrationMetadata.Id
        {
            get { return "202009081544243_AddRemarksField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
